In [12]:
import pandas as pd
import numpy

In [13]:
filename="Recopilación coca cola.xlsx"
dirname="exports"

In [14]:

df=pd.read_excel(filename,1)
df['Trimestre']=df['Tiempo'].str[:1]
df['Tiempo']=df['Tiempo'].str[3:]
df.rename(columns={"Utilidad de operación " :"Utilidad_de_operacion","Ingresos totales":"Ingresos_totales","Utilidad bruta":"Utilidad_bruta","EBITDA Ajustado":"EBITDA"},inplace=True)
df=df[['Trimestre','Tiempo','Ingresos_totales','Utilidad_bruta','Utilidad_de_operacion','EBITDA']]
df=df.fillna("N/A")
print(df)

df.to_excel("exports/ResultadosGenerales.xlsx",index=False,engine="openpyxl")
df.to_csv("mineria/resultados_trimestre.csv")
queryResultados="INSERT INTO RESULTADOS VALUES"

for idx in df.index:
    row=df.loc[idx]
    queryResultados+="({tiempo},{trimestre},{Ingresos},{UBruta},{UOperacion},{EBI},'Global'),\n".format(trimestre=row['Trimestre'],tiempo=row['Tiempo'],Ingresos=row['Ingresos_totales'],UBruta=row['Utilidad_bruta'],UOperacion=row['Utilidad_de_operacion'],EBI=row['EBITDA'])
    
print(queryResultados)

   Trimestre Tiempo  Ingresos_totales  Utilidad_bruta  Utilidad_de_operacion  \
0          2   2024      69455.803129    31961.302174            9745.981766
1          1   2024      63802.606121    28428.378309            8616.614409
2          4   2023      66078.000000    30475.000000            9674.000000
3          3   2023      62853.010851    28847.885532            8459.569001
4          2   2023      61428.388020    27267.402891            8562.036239
5          1   2023      57357.397600    25458.179364            7724.222120
6          4   2022      61209.427902    27067.925048            9013.477503
7          3   2022      57093.487328    25391.849113            7334.888361
8          2   2022      57310.599224    25271.381289            7652.482268
9          1   2022      51195.451134    22602.156377            6843.593762
10         4   2021      53272.691552    23984.526559            7777.931586
11         3   2021      48315.596639    21816.667297            6476.075171
12         2   2021      47786.358994    22559.993448            7248.080240
13         1   2021      44690.406937    19921.990934            5899.104493
14         4   2020      49115.552469    21938.932476            7228.866063
15         3   2020      46734.010846    21367.214762            7119.135833
16         2   2020      43074.655002    19075.033670            5130.032412
17         1   2020      45348.189320    20713.713028            5728.788605
18         4   2019      51735.124745    22928.402601            6372.668451
19         3   2019      48698.552143    21666.794564            7012.677087
20         2   2019      47978.325808    22102.403535            6337.804932
21         1   2019      46247.735621    20892.290059            5714.352697
22         4   2018      50165.632932    23016.556135            7342.001549
23         3   2018      44148.103167    20236.720810            5777.478320
24         2   2018      52085.985437    22950.914246            6276.008952
25         1   2018      49712.868940    21916.687342            5882.556901
26         4   2017      55275.000000    25063.000000            7548.000000

          EBITDA
0   13922.096083
1   11943.572813
2        13149.0
3   11829.809902
4   11438.524637
5   10521.718006
6   11954.455245
7   10626.362279
8   10607.108274
9    9827.392636
10  10648.200344
11   9319.521631
12  10006.982159
13   8807.441707
14   9997.834165
15  10074.686013
16   8221.220565
17   9086.427469
18   9391.054195
19   10069.21785
20   9180.013944
21   8540.581059
22  10215.015326
23   8491.611646
24   9511.216814
25   8705.554457
26           N/A
INSERT INTO RESULTADOS VALUES(2024,2,69455.80312857535,31961.302174470737,9745.98176555364,13922.096083028468,'Global'),
(2024,1,63802.60612148751,28428.378308814594,8616.61440934002,11943.5728128699,'Global'),
(2023,4,66078.0,30475.0,9674.0,13149.0,'Global'),
(2023,3,62853.01085143204,28847.885531935073,8459.56900132275,11829.809901518796,'Global'),
(2023,2,61428.38802000759,27267.402891312213,8562.03623876235,11438.524637146691,'Global'),
(2023,1,57357.397599880795,25458.17936430975,7724.2221202024,10521.718005967907,'Global'),
(2022,4,61209.42790171153,27067.925048019468,9013.47750326499,11954.455245146693,'Global'),
(2022,3,57093.48732772651,25391.849113290347,7334.888360575071,10626.362279236262,'Global'),
(2022,2,57310.59922378635,25271.381289243713,7652.482268096298,10607.108274113332,'Global'),
(2022,1,51195.45113361231,22602.156377482057,6843.593761695654,9827.392636325114,'Global'),
(2021,4,53272.69155211626,23984.526558529866,7777.931586194914,10648.200343573077,'Global'),
(2021,3,48315.596638839466,21816.667296689317,6476.07517063645,9319.521630928804,'Global'),
(2021,2,47786.358993595255,22559.993447875506,7248.0802404757915,10006.982159271894,'Global'),
(2021,1,44690.40693672021,19921.9909338332,5899.104492809429,8807.441706916166,'Global'),
(2020,4,49115.552468539085,21938.932476289367,7228.86606319706,9997.834164877875,'Global'),
(2020,3,46734.010845961835,21367.214761846248,7119.135832770328,10074.686012719721,'Global'),
(2020,2,43074.655001929,19075.033669912315,5130.032411952074,8221.220564662008,'Global'),
(2020,1,45348.18932037066,20713.713027511836,5728.788605381143,9086.42746854843,'Global'),
(2019,4,51735.1247449662,22928.402601123445,6372.668451114874,9391.05419548701,'Global'),
(2019,3,48698.552143166955,21666.794564466232,7012.677086686622,10069.217849966226,'Global'),
(2019,2,47978.325808098336,22102.403535336995,6337.804932222957,9180.013943656655,'Global'),
(2019,1,46247.73562053852,20892.29005949488,5714.352697168594,8540.581058540392,'Global'),
(2018,4,50165.632931969056,23016.55613541045,7342.001548950003,10215.015326160235,'Global'),
(2018,3,44148.103167386806,20236.72080955599,5777.478320144682,8491.611646311303,'Global'),
(2018,2,52085.98543706606,22950.914246265816,6276.00895208458,9511.21681359364,'Global'),
(2018,1,49712.86893964255,21916.68734193612,5882.556900653713,8705.55445693481,'Global'),
(2017,4,55275.0,25063.0,7548.0,N/A,'Global'),

In [15]:
dfResultsMx=pd.read_excel(filename,2)

dfResultsMx['Trimestre']=dfResultsMx['Tiempo'].str[:1]
dfResultsMx['Tiempo']=dfResultsMx['Tiempo'].str[3:]
print(dfResultsMx)
dfResultsMx.to_excel("exports/ResultadosMx.xlsx",index=False,engine="openpyxl")
queryResultadosMx="INSERT INTO resultados VALUES"

for idx in dfResultsMx.index:
    tiempo=dfResultsMx['Tiempo'].loc[idx]
    queryResultadosMx+="({anio},{cuarto},{ingresos},{UBruta},{UOperacion},{EBI},'Mexico'),\n".format(anio=dfResultsMx['Tiempo'].loc[idx],cuarto=dfResultsMx['Trimestre'].loc[idx],ingresos=dfResultsMx['Ingresos totales'].loc[idx],UBruta=dfResultsMx['Utilidad bruta'].loc[idx],UOperacion=dfResultsMx['Utilidad de operación '].loc[idx],EBI=dfResultsMx['EBITDA Ajustado'].loc[idx])

print(queryResultadosMx)

#print(dfResultsMx)

   Tiempo  Ingresos totales  Utilidad bruta  Utilidad de operación   \
0    2024      45066.531142    21947.507218             7290.669497
1    2024      37844.231716    17888.074191             5681.381972
2    2023      37622.000000    18422.000000             5618.000000
3    2023      39035.239521    18688.799341             6031.898860
4    2023      39087.654624    18635.445316             6508.828203
5    2023      33617.462806    15918.717688             5011.059547
6    2022      33792.475485    15678.046618             5212.432388
7    2022      33799.346205    15854.665684             5059.491122
8    2022      34475.152429    16494.981724             5726.748250
9    2022      28934.917286    14006.818722             4949.790422
10   2021      30791.725194    14918.371250             5082.817198
11   2021      28760.019102    14200.500701             4264.702740
12   2021      30262.255527    15175.048615             5132.179968
13   2021      25980.107301    13072.354653             4361.757600
14   2020      27072.565038    13669.501429             4956.081816
15   2020      26806.885526    13302.846564             4335.763938
16   2020      27379.695658    13480.407334             4696.081123
17   2020      25523.975031    12452.955307             3434.788591
18   2019      27253.153653    13050.299992             3524.349354
19   2019      28165.535441    13387.935044             4094.921158
20   2019      29007.964306    14165.673191             4526.727844
21   2019      24822.719061    11780.795196             3076.342307
22   2018          0.000000        0.000000                0.000000
23   2018          0.000000        0.000000                0.000000
24   2018          0.000000        0.000000                0.000000
25   2018          0.000000        0.000000                0.000000
26   2017      23384.000000    11203.000000             3182.000000
27   2019      29007.964306    14165.673191             4526.727844
28   2019      24822.719061    11780.795196             3076.342307
29   2018          0.000000        0.000000                0.000000
30   2018          0.000000        0.000000                0.000000
31   2018          0.000000        0.000000                0.000000
32   2018          0.000000        0.000000                0.000000
33   2017      23384.000000    11203.000000             3182.000000

    EBITDA Ajustado Trimestre
0       9882.158016         2
1       7743.665885         1
2       7704.000000         4
3       8182.473810         3
4       8229.058549         2
5       6706.067337         1
6       6902.489385         4
7       7170.912659         3
8       7533.119938         2
9       6722.426288         1
10      6835.394948         4
11      6061.969655         3
12      6821.101331         2
13      6162.756981         1
14      6612.464861         4
15      6175.476680         3
16      6481.799839         2
17      5603.622026         1
18      5501.673885         4
19      5921.995459         3
20      6284.756327         2
21      4772.236776         1
22         0.000000         4
23         0.000000         3
24         0.000000         2
25         0.000000         1
26      4877.000000         4
27      6284.756327         2
28      4772.236776         1
29         0.000000         4
30         0.000000         3
31         0.000000         2
32         0.000000         1
33      4877.000000         4
INSERT INTO resultados VALUES(2024,2,45066.53114235432,21947.50721825104,7290.669497499773,9882.158015890753,'Mexico'),
(2024,1,37844.23171576212,17888.07419070231,5681.381972133314,7743.665885295243,'Mexico'),
(2023,4,37622.0,18422.0,5618.0,7704.0,'Mexico'),
(2023,3,39035.23952123994,18688.799341222897,6031.898859612582,8182.473809876002,'Mexico'),
(2023,2,39087.65462351632,18635.445316462967,6508.8282026863935,8229.058548564464,'Mexico'),
(2023,1,33617.46280604312,15918.71768827111,5011.05954708278,6706.067336507261,'Mexico'),
(2022,4,33792.47548530963,15678.046618058166,5212.432387525795,6902.489385083605,'Mexico'),
(2022,3,33799.34620532513,15854.665684198175,5059.4911221730645,7170.912659333747,'Mexico'),
(2022,2,34475.15242874845,16494.98172440966,5726.748249617064,7533.119937699374,'Mexico'),
(2022,1,28934.917286451073,14006.818721884822,4949.790421781691,6722.426287739892,'Mexico'),
(2021,4,30791.72519381558,14918.371249672244,5082.817197610317,6835.3949481293985,'Mexico'),
(2021,3,28760.019102274735,14200.500700949957,4264.702739915021,6061.969655397579,'Mexico'),
(2021,2,30262.255526788973,15175.048615318217,5132.179968356454,6821.101330625191,'Mexico'),
(2021,1,25980.107301336437,13072.354653415612,4361.757600089908,6162.756981398439,'Mexico'),
(2020,4,27072.565038462657,13669.501429387477,4956.081815993917,6612.464861135244,'Mexico'),
(2020,3,26806.885525685047,13302.846564147489,4335.7639382954185,6175.4766800391235,'Mexico'),
(2020,2,27379.69565770218,13480.407333806475,4696.081123022391,6481.799838760074,'Mexico'),
(2020,1,25523.975031399306,12452.955307487506,3434.788591427987,5603.622026332354,'Mexico'),
(2019,4,27253.15365329295,13050.299992054011,3524.349354249953,5501.673884838423,'Mexico'),
(2019,3,28165.535440645097,13387.935044404596,4094.921157765147,5921.995458536547,'Mexico'),
(2019,2,29007.964305584348,14165.673190938416,4526.727844216127,6284.756327152787,'Mexico'),
(2019,1,24822.719061463475,11780.795196080637,3076.342306830987,4772.236775545555,'Mexico'),
(2018,4,0.0,0.0,0.0,0.0,'Mexico'),
(2018,3,0.0,0.0,0.0,0.0,'Mexico'),
(2018,2,0.0,0.0,0.0,0.0,'Mexico'),
(2018,1,0.0,0.0,0.0,0.0,'Mexico'),
(2017,4,23384.0,11203.0,3182.0,4877.0,'Mexico'),
(2019,2,29007.964305584348,14165.673190938416,4526.727844216127,6284.756327152787,'Mexico'),
(2019,1,24822.719061463475,11780.795196080637,3076.342306830987,4772.236775545555,'Mexico'),
(2018,4,0.0,0.0,0.0,0.0,'Mexico'),
(2018,3,0.0,0.0,0.0,0.0,'Mexico'),
(2018,2,0.0,0.0,0.0,0.0,'Mexico'),
(2018,1,0.0,0.0,0.0,0.0,'Mexico'),
(2017,4,23384.0,11203.0,3182.0,4877.0,'Mexico'),

In [16]:
dfResultsSa=pd.read_excel(filename,3)
dfResultsSa=dfResultsSa.transpose()
dfResultsSa.columns=dfResultsSa.iloc[0,:]
dfResultsSa=dfResultsSa.iloc[2:,:]
dfResultsSa.reset_index(names="index",inplace=True)
dfResultsSa=dfResultsSa.rename_axis(None,axis="columns")
dfResultsSa.rename(columns={"index":"Tiempo","EBITDA Ajustado (2)":"EBITDA"},inplace=True)

dfResultsSa['Trimestre']=dfResultsSa['Tiempo'].str[:1]
dfResultsSa['Tiempo']=dfResultsSa['Tiempo'].str[3:]
dfResultsSa.fillna('0',inplace=True)

dfResultsSa.to_excel("exports/ResultadosSa.xlsx",index=False,engine="openpyxl")
print(dfResultsSa)

queryResultadosSa="INSERT INTO resultados VALUES"

for idx in dfResultsSa.index:
    row=dfResultsSa.loc[idx]
    queryResultadosSa+="({anio},{cuarto},{ingresos},{UBruta},{UOperacion},{EBI},'Sudamerica'),\n".format(anio=row['Tiempo'],cuarto=row['Trimestre'],ingresos=row['Ingresos totales'],UBruta=row['Utilidad bruta'],UOperacion=row['Utilidad de operación '],EBI=row['EBITDA'])


print(queryResultadosSa)

   Tiempo Ingresos totales Utilidad bruta Utilidad de operación        EBITDA  \
0    2024     24389.271986   10013.794956            2455.312268  4039.938067
1    2024     25958.374406   10540.304118            2935.232437  4199.906928
2    2023            28456          12054                   4056         5444
3    2023      23817.77133   10159.086191            2427.670142  3647.336092
4    2023     22340.733396    8631.957575            2053.208036  3209.466089
5    2023     23739.934794    9539.461676            2713.162573  3815.650669
6    2022     27416.952416    11389.87843            3801.045116   5051.96586
7    2022     23294.141122    9537.183429            2275.397238   3455.44962
8    2022     22835.446795    8776.399565            1925.734018  3073.988336
9    2022     22260.533847    8595.337656             1893.80334  3104.966349
10   2021     22480.966358    9066.155309            2695.114389  3812.805395
11   2021     19555.577537    7616.166596            2211.372431  3257.551976
12   2021     17524.103467    7384.944833            2115.900272  3185.880829
13   2021     18710.299635     6849.63628            1537.346893  2644.684726
14   2020      22042.98743    8269.431047            2272.784247  3385.369304
15   2020      19927.12532    8064.368198            2783.371894  3899.209333
16   2020     15694.959344    5594.626336             433.951289  1739.420726
17   2020     19824.214289     8260.75772            2294.000014  3482.805442
18   2019     24481.971092    9878.102609            2848.319097  3889.380311
19   2019     20533.016703     8278.85952            2917.755929  4147.222391
20   2019     18970.361503    7936.730344            1811.077088  2895.257617
21   2019     21425.016559    9111.494863             2638.01039  3768.344283
22   2018                0              0                      0            0
23   2018                0              0                      0            0
24   2018                0              0                      0            0
25   2018                0              0                      0            0
26   2017            25784          11425                   4137         5543

   Trimestre
0          2
1          1
2          4
3          3
4          2
5          1
6          4
7          3
8          2
9          1
10         4
11         3
12         2
13         1
14         4
15         3
16         2
17         1
18         4
19         3
20         2
21         1
22         4
23         3
24         2
25         1
26         1
INSERT INTO resultados VALUES(2024,2,24389.271986221036,10013.794956219697,2455.312268053869,4039.938067137713,'Sudamerica'),
(2024,1,25958.3744057254,10540.304118112279,2935.2324372067046,4199.906927574656,'Sudamerica'),
(2023,4,28456,12054,4056,5444,'Sudamerica'),
(2023,3,23817.771330192103,10159.086190712178,2427.6701417101676,3647.3360916427955,'Sudamerica'),
(2023,2,22340.733396491265,8631.957574849239,2053.208036075955,3209.4660885822263,'Sudamerica'),
(2023,1,23739.93479383767,9539.46167603864,2713.1625731196186,3815.6506694606464,'Sudamerica'),
(2022,4,27416.95241640189,11389.8784299613,3801.045115739195,5051.965860063089,'Sudamerica'),
(2022,3,23294.141122401383,9537.183429092165,2275.397238402006,3455.4496199025157,'Sudamerica'),
(2022,2,22835.446795037904,8776.399564834051,1925.7340184792324,3073.9883364139573,'Sudamerica'),
(2022,1,22260.533847161252,8595.337655597234,1893.8033399139629,3104.96634858522,'Sudamerica'),
(2021,4,22480.966358300673,9066.15530885762,2695.1143885845972,3812.8053954436773,'Sudamerica'),
(2021,3,19555.577536564728,7616.16659573936,2211.372430721428,3257.5519755312253,'Sudamerica'),
(2021,2,17524.103466806286,7384.944832557295,2115.900272119337,3185.880828646705,'Sudamerica'),
(2021,1,18710.29963538377,6849.636280417588,1537.3468927195217,2644.684725517728,'Sudamerica'),
(2020,4,22042.987430076424,8269.431046901882,2272.784247203143,3385.3693037426306,'Sudamerica'),
(2020,3,19927.125320276777,8064.36819769876,2783.3718944749103,3899.2093326805953,'Sudamerica'),
(2020,2,15694.959344226825,5594.626336105838,433.95128892968387,1739.4207259019347,'Sudamerica'),
(2020,1,19824.214288971358,8260.757720024332,2294.0000139531544,3482.805442216073,'Sudamerica'),
(2019,4,24481.97109167325,9878.10260906943,2848.3190968649205,3889.3803106485875,'Sudamerica'),
(2019,3,20533.01670252185,8278.859520061635,2917.7559289214746,4147.222391429679,'Sudamerica'),
(2019,2,18970.361502513984,7936.730344398575,1811.0770880068308,2895.257616503869,'Sudamerica'),
(2019,1,21425.016559075048,9111.494863414238,2638.010390337607,3768.344282994839,'Sudamerica'),
(2018,4,0,0,0,0,'Sudamerica'),
(2018,3,0,0,0,0,'Sudamerica'),
(2018,2,0,0,0,0,'Sudamerica'),
(2018,1,0,0,0,0,'Sudamerica'),
(2017,1,25784,11425,4137,5543,'Sudamerica'),

In [17]:
dfkof=pd.read_excel(filename,4)
dfkof=dfkof.transpose()
dfkof.columns=dfkof.iloc[0,:]
dfkof=dfkof.iloc[2:,:-3]
dfkof.reset_index(inplace=True)
dfkof.rename(columns={'index':"Tiempo"},inplace=True)
dfkof=dfkof.rename_axis(None,axis="columns")

dfkof['Trimestre']=dfkof['Tiempo'].str[0]
dfkof['Tiempo']=dfkof['Tiempo'].str[3:]
dfkof.to_excel("exports/KofGeneral.xlsx",index=False,engine="openpyxl")
print(dfkof)

   Tiempo Transacciones (millones de transacciones)   \
0    2024                                6372.795488
1    2024                                5958.003244
2    2023                                     6194.6
3    2023                                6048.581099
4    2023                                5933.022568
5    2023                                5567.286363
6    2022                                 5987.70124
7    2022                                5507.295969
8    2022                                     5636.1
9    2022                                5205.255575
10   2021                                5564.271514
11   2021                                4891.594668
12   2021                                4659.978368
13   2021                                4375.044175
14   2020                                4924.541944
15   2020                                4185.223174
16   2020                                3636.909617
17   2020                                4652.438774
18   2019                                5333.245369
19   2019                                5037.755529
20   2019                                5012.472874
21   2019                                4837.776355
22   2018                                5186.706461
23   2018                                4973.103219
24   2018                                6699.146469
25   2018                                6137.567497
26   2017                                    25875.3

   Volumen (milliones de cajas unidad)  Precio promedio por caja unidad  \
0                           1095.809914                       61.892618
1                           1008.632687                        61.21283
2                                1056.2                           60.24
3                           1033.073778                        58.86734
4                           1018.935511                       58.311031
5                               939.601                       59.275595
6                            995.308578                       59.542344
7                            925.827227                       60.153154
8                                 952.4                       60.046315
9                            881.625334                        56.51779
10                           951.338399                       54.305177
11                           854.469064                       52.937723
12                           851.415553                       51.784771
13                           800.655275                       50.838001
14                           902.179622                       49.831391
15                            807.92233                       51.166682
16                           780.749527                       50.558304
17                           793.545491                       51.883517
18                           889.628868                        52.57234
19                           842.132345                       52.089314
20                           840.884159                       52.823652
21                                796.1                       52.574423
22                           871.726178                       52.185667
23                           839.221098                       48.953614
24                                977.1                       50.293688
25                           907.750808                       50.685122
26                               3870.6                           49.29

    Ventas netas Otros ingresos de operación  Ingresos totales (2)  \
0   69296.507901                   159.295228         69455.803129
1   63637.930214                   164.675908         63802.606121
2          65830                          248                66078
3    62611.95539                   241.055461         62853.010851
4    61283.06363                    145.32439          61428.38802
5   57145.071106                   212.326493           57357.3976
6   61005.382101                   204.045801         61209.427902
7   57016.624308                     76.86302         57093.487328
8   57190.036475                   120.562749         57310.599224
9   51077.676924                    117.77421         51195.451134
10  53091.978985                   180.712568         53272.691552
11  47916.290089                    399.30655         48315.596639
12  47639.405601                   146.953392         47786.358994
13  44517.835551                   172.571386         44690.406937
14  49022.065501                    93.486967         49115.552469
15  45247.542407                  1486.468439         46734.010846
16  42943.809047                   130.845955         43074.655002
17  44958.051556                   390.137764          45348.18932
18  51541.125974                   193.998771         51735.124745
19  47294.373218                  1404.178925         48698.552143
20  47671.844171                   306.481637         47978.325808
21  46021.105619                   226.630002         46247.735621
22  49982.250885                   183.382046         50165.632932
23  44011.718635                   136.384533         44148.103167
24  51984.528153                   101.457284         52085.985437
25   49595.94948                    116.91946          49712.86894
26      203374.0                        406.0             203780.0

   Costo de ventas Utilidad bruta Gastos de operación   ...  \
0     37494.500954   31961.302174         21620.579089  ...
1     35374.227813   28428.378309         19668.011631  ...
2            35603          30475                20413  ...
3     34005.125319   28847.885532         19969.992286  ...
4     34160.985129   27267.402891          18795.61514  ...
5     31899.218236   25458.179364         17824.884759  ...
6     34141.502854   27067.925048         17867.943902  ...
7     31701.638214   25391.849113            17933.007  ...
8     32039.217935   25271.381289         17448.256011  ...
9     28593.294756   22602.156377          15757.34874  ...
10    29288.164994   23984.526559         15904.540494  ...
11    26498.929342   21816.667297         15530.313303  ...
12    25226.365546   22559.993448          15188.94667  ...
13    24768.416003   19921.990934          13793.04151  ...
14    27176.619992   21938.932476         14374.953245  ...
15    25366.796084   21367.214762         14216.264717  ...
16    23999.621332    19075.03367         13630.475071  ...
17    24634.476293   20713.713028         14535.592758  ...
18    28806.722144   22928.402601         16018.468577  ...
19    27031.757579   21666.794564         14702.509827  ...
20    25875.922273   22102.403535         15036.421341  ...
21    25355.445561   20892.290059         14846.547753  ...
22    27149.076797   23016.556135         15164.876167  ...
23    23911.382358    20236.72081         14255.640561  ...
24    29135.071191   22950.914246         16126.412885  ...
25    27796.181598   21916.687342         15934.240828  ...
26        112094.0        91686.0              64910.0  ...

   (Utilidad) pérdida por posición monetaria en subsidiarias hiperinflacionarias   \
0                                          -34.083325
1                                           -6.616564
2                                                  -4
3                                          -17.091023
4                                          -63.059391
5                                           -59.64346
6                                         -128.475533
7                                         -124.330475
8                                         -138.097288
9                                         -146.931738
10                                        -269.546818
11                                        -117.249443
12                                        -118.116972
13                                        -170.599141
14                                         -123.48615
15                                        -116.608554
16                                         -80.787494
17                                         -97.966459
18                                        -139.032731
19                                        -102.756464
20                                          35.632799
21                                          -5.002455
22                                         -59.133637
23                                        -116.599567
24                                                0.0
25                                                0.0
26                                            -1591.0

   (Utilidad) pérdida en instrumentos financieros   \
0                                       -61.113011
1                                        46.409702
2                                              -90
3                                       -94.682544
4                                        67.969914
5                                       -52.898825
6                                       -72.121215
7                                       156.715798
8                                      -355.464976
9                                        936.49326
10                                     -130.716809
11                                       42.240867
12                                        0.756202
13                                        8.163675
14                                      213.992244
15                                       -0.316195
16                                        0.843893
17                                       -2.037382
18                                      138.914439
19                                      149.928646
20                                       -0.334684
21                                       -0.017607
22                                       67.410892
23                                      -58.985205
24                                       59.332913
25                                      245.806619
26                                          -246.0

   Resultado integral de financiamiento Utilidad antes de impuestos  \
0                            885.079325                  8752.48347
1                           1188.103968                 7505.671277
2                                  1285                        8470
3                            552.457197                 7785.702996
4                           1376.569277                 6926.043055
5                           1398.867819                 6067.418527
6                            1091.57898                 8007.845413
7                            682.226864                 6671.408913
8                            573.801845                 7034.096083
9                           2193.931992                  4473.58135
10                           748.343981                 7053.237557
11                          1029.693971                  5169.96276
12                          1323.241457                 5935.784512
13                          1131.364516                 4765.899303
14                          1777.072381                 5375.071781
15                          1421.285139                 3898.918626
16                           1267.97286                 2889.349433
17                           2196.04732                  3612.77833
18                          1506.832994                   3851.4571
19                          1429.910166                 5564.128923
20                          1558.736481                 4778.913073
21                          1593.415492                 4079.425544
22                          2149.017219                 4603.318128
23                          1322.217212                  4393.86605
24                          1380.665798                 4854.463784
25                           2071.86932                 3737.204879
26                               5276.0                     -7101.0

      Impuestos Resultado de operaciones discontinuas  \
0   3043.634785                                   0.0
1   2258.208578                                   0.0
2          2802                                   -
3   2272.834351                                   0.0
4   1881.148535                                   0.0
5   1989.246378                                   0.0
6    611.359432                                   0.0
7   2166.342391                                   0.0
8   2458.344444                                   0.0
9   1320.943616                                   0.0
10    977.65398                                   0.0
11  1696.912499                                   0.0
12  2267.507808                                   0.0
13  1659.594101                                   0.0
14  1997.240319                                   0.0
15  1320.094836                                   0.0
16   969.488361                                   0.0
17  1122.016737                                   0.0
18  1694.092112                                   0.0
19  1439.178637                                   0.0
20  1181.196245                                   0.0
21  1330.913107                                   0.0
22  1385.892952                           2790.316187
23  1381.737452                            409.699735
24  1663.570577                                   NaN
25   1196.26376                                   NaN
26       4554.0                                   NaN

   Utilidad neta consolidada  \
0                5708.848686
1                5247.462698
2                       5669
3                5512.868645
4                 5044.89452
5                4078.172149
6                7396.485982
7                4505.066522
8                4575.751639
9                3152.637733
10               6075.583577
11               3473.050261
12               3668.276704
13               3106.305201
14               3377.831462
15               2578.823791
16               1919.861072
17               2490.761594
18               2157.364988
19               4124.950287
20               3597.716828
21               2748.512437
22               6007.741363
23               3421.828333
24               3190.893207
25               2540.941118
26                  -11654.0

   Utilidad neta atribuible a la participación controladora  \
0                                          5607.99565
1                                         5006.107188
2                                                5392
3                                         5380.071213
4                                          4926.16062
5                                         3916.014293
6                                         7143.747122
7                                         4374.111649
8                                         4626.687246
9                                           2893.8239
10                                        5808.642803
11                                         3419.24101
12                                        3316.344772
13                                        3155.595621
14                                        3177.062072
15                                        2462.812918
16                                        2114.689793
17                                         2551.74939
18                                        1995.459539
19                                        4026.871158
20                                        3486.946391
21                                        2590.465135
22                                        5541.093824
23                                         3266.06602
24                                        2780.665922
25                                        2413.795189
26                                           -12802.0

   Participación no controladora Trimestre
0                     100.853036         2
1                     241.355511         1
2                            277         4
3                     132.797432         3
4                       118.7339         2
5                     162.157856         1
6                      252.73886         4
7                     130.954874         3
8                     -50.935607         2
9                     258.813833         1
10                    266.940774         4
11                     53.809251         3
12                    351.931932         2
13                     -49.29042         1
14                     200.76939         4
15                    116.010873         3
16                   -194.828721         2
17                    -60.987796         1
18                    161.905449         4
19                     98.079129         3
20                    110.770437         2
21                    158.047302         1
22                    466.647539         4
23                    155.762313         3
24                    410.227285         2
25                     127.14593         1
26                        1148.0         4

[27 rows x 29 columns]

In [18]:
dfkofMXCA=pd.read_excel(filename,5)
dfkofMXCA=dfkofMXCA.transpose()
dfkofMXCA.columns=dfkofMXCA.iloc[0,:]
dfkofMXCA=dfkofMXCA.iloc[2:-1,:-3]
dfkofMXCA.reset_index(inplace=True)
dfkofMXCA=dfkofMXCA.rename_axis(None,axis="columns")
dfkofMXCA=dfkofMXCA[dfkofMXCA['index'].str[0] != "%"]
dfkofMXCA.rename(columns={'index':"Tiempo"},inplace=True)
dfkofMXCA.reset_index(drop=True,inplace=True)

dfkofMXCA['Trimestre']=dfkofMXCA['Tiempo'].str[0]
dfkofMXCA['Tiempo']=dfkofMXCA['Tiempo'].str[:]
dfkofMXCA.to_excel("exports/KofMxCa.xlsx",index=False,engine="openpyxl")

print(dfkofMXCA)

     Tiempo Transacciones (milliones de transacciones)   \
0   2T 2024                                 3565.344497
1   1T 2024                                 3019.091418
2   4T 2023                                      2981.7
3   3T 2023                                 3232.778604
4   2T 2023                                  3303.59573
5   1T 2023                                 2826.817025
6   4T 2022                                 2921.184747
7   3T 2022                                 2937.088436
8   2T 2022                                      3126.6
9   1T 2022                                 2648.320558
10  4T 2021                                 2816.394016
11  3T 2021                                 2619.001965
12  2T 2021                                 2790.683379
13  1T 2021                                 2383.948122
14  4T 2020                                 2486.583083
15  3T 2020                                 2408.896659
16  2T 2020                                 2346.746752
17  1T 2020                                 2597.531205
18  4T 2019                                 2834.245023
19  3T 2019                                 2946.307298
20  2T 2019                                 3060.625285
21  1T 2019                                 2688.408566
22  4T 2018                                 2807.440407
23  3T 2018                                 2953.811179
24  2T 2018                                 3072.193674
25  1T 2018                                 2674.021229
26  4T 2017                                     2,763,9

   Volumen (milliones de cajas unidad)  Precio promedio por caja unidad  \
0                            695.589768                       64.480896
1                             579.84253                       64.917498
2                                 580.9                           64.28
3                            633.213534                       61.280878
4                            643.283031                       60.442937
5                            537.383895                       62.547941
6                            547.862935                       61.689115
7                            555.787811                        60.79892
8                                 590.7                       58.348422
9                            494.034575                       58.552412
10                           531.780858                       57.853601
11                           508.992533                       56.467756
12                           545.804282                       55.422852
13                           471.299774                       55.110325
14                           494.967226                       54.631904
15                           498.644935                       53.720566
16                           521.644878                       52.451856
17                           476.398984                       53.551588
18                           506.896487                        53.73445
19                           535.716685                       52.534788
20                           554.707977                        52.28108
21                           477.975007                       51.860471
22                           503.765573                       50.401164
23                           534.134606                       48.782346
24                           552.203731                       47.778001
25                           474.870504                       46.893939
26                                495.1                           47.16

    Ventas netas Otros ingresos de operación Ingresos totales (2)  \
0    45077.92409                  -11.392948         45066.531142
1   37844.253669                   -0.021953         37844.231716
2        37603.0                        19.0              37622.0
3    39023.87634                   11.363181         39035.239521
4   39081.164052                    6.490571         39087.654624
5   33612.256032                    5.206774         33617.462806
6   33797.179649                   -4.704164         33792.475485
7   33791.298435                     8.04777         33799.346205
8   34465.706096                    9.446333         34475.152429
9   28926.916171                    8.001115         28934.917286
10  30765.437685                   26.287509         30791.725194
11  28741.666102                      18.353         28760.019102
12  30250.030129                   12.225398         30262.255527
13  25973.483699                    6.623603         25980.107301
14  27041.002198                    31.56284         27072.565038
15  26788.339587                   18.545938         26806.885526
16  27363.135716                   16.559942         27379.695658
17  25511.921993                   12.053038         25523.975031
18  27237.804109                   15.349544         27253.153653
19  28143.762669                   21.772772         28165.535441
20  29000.731899                    7.232406         29007.964306
21  24788.008939                   34.710122         24822.719061
22  25390.371325                   33.940348         25424.311673
23  26056.339327                    12.52268         26068.862007
24  26383.190532                    8.582815         26391.773347
25  22268.548279                    8.899815         22277.448094
26         23347                          37                23348

   Costo de ventas Utilidad bruta Gastos de operación  \
0     23119.023924   21947.507218        14240.622866
1     19956.157525   17888.074191        12113.817989
2          19200.0        18422.0             12663.0
3      20346.44018   18688.799341        12369.857332
4     20452.209307   18635.445316        12251.839473
5     17698.745118   15918.717688         11058.64622
6     18114.428867   15678.046618        10451.097572
7     17944.680521   15854.665684        10710.234653
8     17980.170704   16494.981724        10562.049673
9     14928.098565   14006.818722         9105.463582
10    15873.353944    14918.37125          9666.37776
11    14559.518401   14200.500701         9811.046638
12    15087.206911   15175.048615         9999.972506
13    12907.752648   13072.354653         8571.928469
14    13403.063609   13669.501429         8583.784005
15    13504.038962   13302.846564         8860.353484
16    13899.288324   13480.407334          8614.12005
17    13071.019724   12452.955307         8571.104413
18    14202.853661   13050.299992         9256.448326
19    14777.600396   13387.935044         8948.719345
20    14842.291115   14165.673191         9130.012293
21    13041.923865   11780.795196         8555.585024
22    13192.113933    12232.19774         8380.677393
23    13503.346068    12565.51594         8748.275066
24    13511.005318   12880.768029         8719.016684
25    11793.608179   10483.839914         7866.332786
26           12181          11203                7680

   Otros gastos operativos, neto  \
0                     477.844644
1                      119.10051
2                          150.0
3                     343.985035
4                    -100.926664
5                    -111.318674
6                      39.094026
7                     120.531257
8                       236.1531
9                      -2.107494
10                    203.204287
11                    160.898227
12                     62.114891
13                    189.231554
14                     55.655146
15                     95.775349
16                    128.472261
17                    386.190426
18                    185.869226
19                    299.732276
20                    422.111529
21                    112.439328
22                    285.998997
23                    -31.334377
24                     276.19546
25                    -103.49911
26                           215

   Método de participación operativo (utilidad) pérdida en los resultados de asociadas (3)  \
0                                          -61.629789
1                                           -26.22628
2                                                -9.0
3                                          -56.941886
4                                          -24.295696
5                                          -39.669405
6                                          -24.577367
7                                          -35.591347
8                                          -29.969299
9                                          -46.327788
10                                         -34.027995
11                                         -36.146904
12                                          -19.21875
13                                          -50.56297
14                                          73.980463
15                                          10.953792
16                                            41.7339
17                                          60.871877
18                                          83.633086
19                                          44.562266
20                                          86.821524
21                                          36.428537
22                                         161.165382
23                                          99.052917
24                                          85.446643
25                                          58.959227
26                                                126

   Utilidad de operación (4)  \
0                7290.669497
1                5681.381972
2                     5618.0
3                 6031.89886
4                6508.828203
5                5011.059547
6                5212.432388
7                5059.491122
8                 5726.74825
9                4949.790422
10               5082.817198
11                4264.70274
12               5132.179968
13                 4361.7576
14               4956.081816
15               4335.763938
16               4696.081123
17               3434.788591
18               3524.349354
19               4094.921158
20               4526.727844
21               3076.342307
22               3404.355967
23               3749.522334
24               3800.109242
25               2662.047011
26                      3182

   Depreciación, amortización y otros cargos virtuales EBITDA Ajustado (4)(5)  \
0                                         2591.488518             9882.158016
1                                         2062.283913             7743.665885
2                                              2086.0                  7704.0
3                                          2150.57495              8182.47381
4                                         1720.230346             8229.058549
5                                         1695.007789             6706.067337
6                                         1690.056998             6902.489385
7                                         2111.421537             7170.912659
8                                         1806.371688             7533.119938
9                                         1772.635866             6722.426288
10                                        1752.577751             6835.394948
11                                        1797.266915             6061.969655
12                                        1688.921362             6821.101331
13                                        1800.999381             6162.756981
14                                        1656.383045             6612.464861
15                                        1839.712742              6175.47668
16                                        1785.718716             6481.799839
17                                        2168.833435             5603.622026
18                                        1977.324531             5501.673885
19                                        1827.074301             5921.995459
20                                        1758.028483             6284.756327
21                                        1695.894469             4772.236776
22                                        1900.902961             5305.258929
23                                        1652.542017             5402.064351
24                                        1813.639863             5613.749104
25                                        1434.229956             4096.276967
26                                               1695                    4887

   Trimestre
0          2
1          1
2          4
3          3
4          2
5          1
6          4
7          3
8          2
9          1
10         4
11         3
12         2
13         1
14         4
15         3
16         2
17         1
18         4
19         3
20         2
21         1
22         4
23         3
24         2
25         1
26         4

In [19]:
dfkofSA=pd.read_excel(filename,6)
dfkofSA=dfkofSA.transpose()
dfkofSA.columns=dfkofSA.iloc[0,:]
dfkofSA=dfkofSA.iloc[2:,:-3]
dfkofSA.reset_index(inplace=True)
dfkofSA=dfkofSA.rename_axis(None,axis="columns")
dfkofSA=dfkofSA[dfkofSA['index'].str[0] != "%"]
dfkofSA.rename(columns={'index':"Tiempo"},inplace=True)
dfkofSA.reset_index(drop=True,inplace=True)

dfkofSA['Trimestre']=dfkofSA['Tiempo'].str[0]
dfkofSA['Tiempo']=dfkofSA['Tiempo'].str[3:]
dfkofSA.to_excel("exports/kofSa.xlsx",index=False,engine="openpyxl")
print(dfkofSA)

   Tiempo Transacciones (milliones de transacciones)   \
0    2024                                 2807.450991
1    2024                                 2938.911826
2    2023                                      3212.9
3    2023                                 2815.802495
4    2023                                 2629.426839
5    2023                                 2740.469338
6    2022                                 3066.516493
7    2022                                 2570.207533
8    2022                                 2509.541986
9    2022                                 2556.935018
10   2021                                 2747.877498
11   2021                                 2272.592703
12   2021                                  1869.29499
13   2021                                 1991.096053
14   2020                                 2437.958861
15   2020                                 1776.326515
16   2020                                 1290.162864
17   2020                                 2054.907568
18   2019                                 2499.000346
19   2019                                 2091.448232
20   2019                                 1951.847589
21   2019                                 2149.367789
22   2018                                 2379.266055
23   2018                                  2019.29204
24   2018                                 1808.196743
25   2018                                 2011.456424
26   2017                                      2360.1

   Volumen (milliones de cajas unidad)  Precio promedio por caja unidad  \
0                            400.220146                       57.394144
1                            428.790157                       56.203096
2                                 475.3                           55.32
3                            399.860244                       55.045293
4                             375.65248                       54.660264
5                            402.217105                       54.903564
6                            447.445643                       56.913787
7                            370.039416                       59.183235
8                            361.744191                       59.274498
9                            387.590758                         53.9244
10                            419.55754                       49.807619
11                           345.476531                       45.229056
12                           305.611272                       45.287364
13                             329.3555                       44.724409
14                           407.212396                       43.996361
15                           309.261542                       47.048739
16                           259.118404                        46.74603
17                           317.146507                       49.377838
18                           382.732381                       51.033224
19                           306.415661                       51.310478
20                           286.176182                       53.875343
21                           318.106236                       53.650281
22                           367.960604                       54.628785
23                           305.086492                       49.253464
24                                270.8                       56.285163
25                           313.025744                       57.983613
26                                378.2                           57.56

    Ventas netas Otros ingresos de operación Ingresos totales (2)  \
0   24218.583811                  170.688175         24389.271986
1   25793.676545                  164.697861         25958.374406
2        28227.0                       229.0              28456.0
3    23588.07905                   229.69228          23817.77133
4   22201.899578                  138.833819         22340.733396
5   23532.815074                  207.119719         23739.934794
6   27208.202452                  208.749965         27416.952416
7   23225.325873                    68.81525         23294.141122
8   22724.330379                  111.116416         22835.446795
9   22150.760752                  109.773095         22260.533847
10    22326.5413                  154.425059         22480.966358
11  19174.623987                   380.95355         19555.577537
12  17389.375473                  134.727994         17524.103467
13  18544.351853                  165.947783         18710.299635
14  21981.063303                   61.924127          22042.98743
15   18459.20282                 1467.922501          19927.12532
16  15580.673331                  114.286013         15694.959344
17  19446.129563                  378.084726         19824.214289
18  24303.321865                  178.649227         24481.971092
19   19150.61055                 1382.406153         20533.016703
20  18671.112272                   299.24923         18970.361503
21   21233.09668                  191.919879         21425.016559
22   24591.87956                  149.441699         24741.321259
23  17955.379307                  123.861852          18079.24116
24  18084.587873                   92.874469         18177.462342
25  21736.852636                  108.019645          21844.87228
26       25682.0                       103.0              25784.0

   Costo de ventas Utilidad bruta Gastos de operación  \
0      14375.47703   10013.794956         7379.956223
1     15418.070288   10540.304118         7554.193642
2          16403.0        12054.0              7750.0
3     13658.685139   10159.086191         7600.134954
4     13708.775822    8631.957575         6543.775667
5     14200.473118    9539.461676         6766.238539
6     16027.073986    11389.87843          7416.84633
7     13756.957693    9537.183429         7222.772347
8      14059.04723    8776.399565         6886.206338
9     13665.196192    8595.337656         6651.885158
10    13414.811049    9066.155309         6238.162734
11    11939.410941    7616.166596         5719.266666
12    10139.158634    7384.944833         5188.974164
13    11860.663355     6849.63628          5221.11304
14    13773.556383    8269.431047          5791.16924
15    11862.757123    8064.368198         5355.911233
16    10100.333008    5594.626336         5016.355021
17    11563.456569     8260.75772         5964.488346
18    14603.868483    9878.102609         6762.020251
19    12254.157182     8278.85952         5753.790482
20    11033.631158    7936.730344         5906.409048
21    12313.521696    9111.494863         6290.962729
22    13956.962863   10784.358396         6784.198774
23     10408.03629     7671.20487         5507.365495
24     10201.02732    7976.435023          5648.83586
25    12113.358888    9731.513392         6503.771469
26         14359.0        11425.0              7098.0

   Otros gastos operativos, neto  \
0                     194.648102
1                      68.402519
2                          284.0
3                     156.194958
4                      54.565535
5                      81.149544
6                     187.161907
7                      46.216108
8                      23.355017
9                      23.876103
10                    119.340306
11                   -297.234989
12                     89.663414
13                     22.894089
14                     174.08774
15                     -92.35819
16                     77.222845
17                     -69.46484
18                    252.077825
19                   -362.952666
20                    233.034997
21                    197.367224
22                    116.165968
23                    149.790565
24                    193.874564
25                    134.792307
26                         214.0

   Método de participación operativo (utilidad) pérdida en los resultados de asociadas (3)  \
0                                          -16.121637
1                                           -17.52448
2                                               -36.0
3                                          -24.913863
4                                          -19.591663
5                                          -21.088979
6                                          -15.174922
7                                           -7.202264
8                                          -58.895809
9                                           25.773054
10                                           13.53788
11                                         -17.237632
12                                          -9.593018
13                                          68.282258
14                                           31.38982
15                                           17.44326
16                                          67.097181
17                                            71.7342
18                                          15.685436
19                                         -29.734225
20                                         -13.790789
21                                          -14.84548
22                                         -53.651929
23                                         -13.907176
24                                          -18.18246
25                                         -10.309314
26                                              -24.0

   Utilidad de operación (4)  \
0                2455.312268
1                2935.232437
2                     4056.0
3                2427.670142
4                2053.208036
5                2713.162573
6                3801.045116
7                2275.397238
8                1925.734018
9                 1893.80334
10               2695.114389
11               2211.372551
12               2115.900272
13               1537.346893
14               2272.784247
15               2783.371894
16                433.951289
17               2294.000014
18               2848.319097
19               2917.755929
20               1811.077088
21                2638.01039
22               3937.645582
23               2027.955986
24               2151.907058
25               3103.258929
26                    4137.0

   Depreciación, amortización y otros cargos virtuales Trimestre
0                                         1584.625799          2
1                                          1264.67449          1
2                                              1389.0          4
3                                          1219.66595          3
4                                         1156.258053          2
5                                         1102.488096          1
6                                         1250.920744          4
7                                         1180.052382          3
8                                         1148.254318          2
9                                         1211.163009          1
10                                        1117.691007          4
11                                        1046.179545          3
12                                        1069.980557          2
13                                        1107.337833          1
14                                        1112.585057          4
15                                        1115.837438          3
16                                        1305.469437          2
17                                        1188.805428          1
18                                        1041.061214          4
19                                        1229.466463          3
20                                        1084.180528          2
21                                        1130.333893          1
22                                         972.110816          4
23                                        1061.591309          3
24                                         960.538028          2
25                                         964.957509          1
26                                             1407.0          4

In [20]:
dfvolumen=pd.read_excel(filename,7)
#Columns ideales: País, trimestre, año, producto, cantidad
dfobjetivo=pd.DataFrame(columns=["trimestre","anio","producto","cantidad"])
transposedDf=dfvolumen.transpose()
#transposedDf=transposedDf.iloc[1:,:]
transposedDf[0]=transposedDf[0].str.replace(' (1)','')
transposedDf[0]=transposedDf[0].str.replace(' (2)','')
transposedDf[0]=transposedDf[0].str.replace('(1)','')
transposedDf[0]=transposedDf[0].str.replace('(2)','')
transposedDf.reset_index(inplace=True)

transposedDf.replace('Unnamed: [0-9][0-9][0-9]|Unnamed: [0-9][0-9]|Unnamed: [0-9]','NaN',regex=True,inplace=True)
#transposedDf['index']=transposedDf['index'].str[0:3]
rellenar=""
for idx in transposedDf.index:
    if transposedDf['index'].iloc[idx] == 'NaN':
        transposedDf.loc[idx,'index'] = rellenar
    else:
        rellenar=transposedDf['index'].iloc[idx]
        #print(rellenar)


dfobjetivo['producto']=transposedDf[0]
dfobjetivo['Tiempo']=transposedDf['index']
dfobjetivo['trimestre']=dfobjetivo['Tiempo'].str[0]
dfobjetivo['anio']=dfobjetivo['Tiempo'].str[3:]

dfmexico=dfobjetivo.copy()
dfmexico['cantidad']=transposedDf[1]
dfmexico=dfmexico.iloc[2:,:-1]
dfmexico.insert(0,"pais",'Mexico')
dfmexico.dropna

dfguatemala=dfobjetivo.copy()
dfguatemala['cantidad']=transposedDf[2]
dfguatemala=dfguatemala.iloc[2:,:-1]
dfguatemala.insert(0,"pais",'Guatemala')

dfcolombia=dfobjetivo.copy()
dfcolombia['cantidad']=transposedDf[5]
dfcolombia=dfcolombia.iloc[2:,:-1]
dfcolombia.insert(0,"pais",'Colombia')

dfbrasil=dfobjetivo.copy()
dfbrasil['cantidad']=transposedDf[6]
dfbrasil=dfbrasil.iloc[2:,:-1]
dfbrasil.insert(0,"pais",'Brasil')

dfargentina=dfobjetivo.copy()
dfargentina['cantidad']=transposedDf[7]
dfargentina=dfargentina.iloc[2:,:-1]
dfargentina.insert(0,"pais",'Argentina')

dfuruguay=dfobjetivo.copy()
dfuruguay['cantidad']=transposedDf[8]
dfuruguay=dfuruguay.iloc[2:,:-1]
dfuruguay.insert(0,"pais",'Uruguay')

dfFinal=pd.concat([dfmexico,dfguatemala,dfcolombia,dfbrasil,dfargentina,dfuruguay],ignore_index=True)

dfFinal.to_excel("exports/volumen.xlsx",index=False)
dfFinal.to_csv("mineria/volumen.csv",index=False)

print(dfFinal)
#print(transposedDf)
#dfobjetivo['producto']
#print(dfobjetivo)
#print(dfvolumen.columns)
#print(dfvolumen)

        pais trimestre  anio   producto    cantidad
0     Mexico         2  2024  Refrescos  402.250573
1     Mexico         2  2024       Agua   44.080285
2     Mexico         2  2024   Garrafón  108.094343
3     Mexico         2  2024      Otros   45.039409
4     Mexico         2  2024      Total   599.46461
..       ...       ...   ...        ...         ...
805  Uruguay         4  2017  Refrescos         NaN
806  Uruguay         4  2017       Agua         NaN
807  Uruguay         4  2017   Garrafón         NaN
808  Uruguay         4  2017      Otros         NaN
809  Uruguay         4  2017      Total         NaN

[810 rows x 5 columns]

In [21]:
dfVolumenMexico=dfFinal[dfFinal['pais']=="Mexico"]
dfVolumen2022=dfFinal[dfFinal['anio']=="2022"]
dfVolumenRefresco=dfFinal[(dfFinal['producto']=="Refrescos") | (dfFinal['anio']=="2022")]
print(dfVolumenRefresco)

        pais trimestre  anio   producto    cantidad
0     Mexico         2  2024  Refrescos  402.250573
5     Mexico         1  2024  Refrescos  332.488406
10    Mexico         4  2023  Refrescos       346.1
15    Mexico         3  2023  Refrescos  377.240358
20    Mexico         2  2023  Refrescos  375.913702
..       ...       ...   ...        ...         ...
785  Uruguay         4  2018  Refrescos   12.058439
790  Uruguay         3  2018  Refrescos    8.724645
795  Uruguay         2  2018  Refrescos         NaN
800  Uruguay         1  2018  Refrescos         NaN
805  Uruguay         4  2017  Refrescos         NaN

[258 rows x 5 columns]

In [22]:
dfTransacciones=pd.read_excel(filename,8)

dfobjetivo=pd.DataFrame(columns=["trimestre","anio","producto","cantidad"])
transposedDf=dfTransacciones.transpose()
#transposedDf=transposedDf.iloc[1:,:]
transposedDf[0]=transposedDf[0].str.replace(' (1)','')
transposedDf[0]=transposedDf[0].str.replace(' (2)','')
transposedDf[0]=transposedDf[0].str.replace('(1)','')
transposedDf[0]=transposedDf[0].str.replace('(2)','')
transposedDf.reset_index(inplace=True)

transposedDf.replace('Unnamed: [0-9][0-9][0-9]|Unnamed: [0-9][0-9]|Unnamed: [0-9]','NaN',regex=True,inplace=True)

rellenar=""
for idx in transposedDf.index:
    if transposedDf['index'].iloc[idx] == 'NaN':
        transposedDf.loc[idx,'index'] = rellenar
    else:
        rellenar=transposedDf['index'].iloc[idx]


dfobjetivo['producto']=transposedDf[0]
dfobjetivo['Tiempo']=transposedDf['index']
dfobjetivo['trimestre']=dfobjetivo['Tiempo'].str[0]
dfobjetivo['anio']=dfobjetivo['Tiempo'].str[3:]

dfmexico=dfobjetivo.copy()
dfmexico['cantidad']=transposedDf[1]
dfmexico=dfmexico.iloc[2:,:-1]
dfmexico.insert(0,"pais",'Mexico')
dfmexico.dropna(subset='producto',inplace=True)

dfguatemala=dfobjetivo.copy()
dfguatemala['cantidad']=transposedDf[2]
dfguatemala=dfguatemala.iloc[2:,:-1]
dfguatemala.insert(0,"pais",'Guatemala')
dfguatemala.dropna(subset='producto',inplace=True)

dfcolombia=dfobjetivo.copy()
dfcolombia['cantidad']=transposedDf[5]
dfcolombia=dfcolombia.iloc[2:,:-1]
dfcolombia.insert(0,"pais",'Colombia')
dfcolombia.dropna(subset='producto',inplace=True)

dfbrasil=dfobjetivo.copy()
dfbrasil['cantidad']=transposedDf[6]
dfbrasil=dfbrasil.iloc[2:,:-1]
dfbrasil.insert(0,"pais",'Brasil')
dfbrasil.dropna(subset='producto',inplace=True)

dfargentina=dfobjetivo.copy()
dfargentina['cantidad']=transposedDf[7]
dfargentina=dfargentina.iloc[2:,:-1]
dfargentina.insert(0,"pais",'Argentina')
dfargentina.dropna(subset='producto',inplace=True)

dfuruguay=dfobjetivo.copy()
dfuruguay['cantidad']=transposedDf[8]
dfuruguay=dfuruguay.iloc[2:,:-1]
dfuruguay.insert(0,"pais",'Uruguay')
dfuruguay.dropna(subset='producto',inplace=True)

dfFinal=pd.concat([dfmexico,dfguatemala,dfcolombia,dfbrasil,dfargentina,dfuruguay],ignore_index=True)

dfFinal.to_excel("exports/transacciones.xlsx",index=False)
dfFinal.to_csv("mineria/transacciones.csv",index=False)

print(dfFinal)

        pais trimestre  anio   producto     cantidad
0     Mexico         2  2024  Refrescos  2230.107353
1     Mexico         2  2024       Agua   297.550085
2     Mexico         2  2024      Otros   313.200771
3     Mexico         2  2024      Total  2840.858209
4     Mexico         1  2024  Refrescos  1867.485107
..       ...       ...   ...        ...          ...
643  Uruguay         1  2018      Total          NaN
644  Uruguay         1  2018  Refrescos          NaN
645  Uruguay         4  2017     Agua            NaN
646  Uruguay         4  2017      Otros          NaN
647  Uruguay         4  2017      Total          NaN

[648 rows x 5 columns]