In [1]:
import pandas as pd
import numpy

In [2]:
filename="Recopilación coca cola.xlsx"

df=pd.read_excel(filename,1)
df['Trimestre']=df['Tiempo'].str[:1]
df['Tiempo']=df['Tiempo'].str[3:]
df.rename(columns={"Utilidad de operación " :"Utilidad_de_operacion","Ingresos totales":"Ingresos_totales","Utilidad bruta":"Utilidad_bruta","EBITDA Ajustado":"EBITDA"},inplace=True)
df=df[['Trimestre','Tiempo','Ingresos_totales','Utilidad_bruta','Utilidad_de_operacion','EBITDA']]
df=df.fillna("N/A")
print(df)

queryResultados="INSERT INTO RESULTADOS VALUES"

for idx in df.index:
    row=df.loc[idx]
    queryResultados+="({tiempo},{trimestre},{Ingresos},{UBruta},{UOperacion},{EBI},'Global'),\n".format(trimestre=row['Trimestre'],tiempo=row['Tiempo'],Ingresos=row['Ingresos_totales'],UBruta=row['Utilidad_bruta'],UOperacion=row['Utilidad_de_operacion'],EBI=row['EBITDA'])
    
print(queryResultados)

   Trimestre Tiempo  Ingresos_totales  Utilidad_bruta  Utilidad_de_operacion  \
0          2   2024      69455.803129    31961.302174            9745.981766
1          1   2024      63802.606121    28428.378309            8616.614409
2          4   2023      66078.000000    30475.000000            9674.000000
3          3   2023      62853.010851    28847.885532            8459.569001
4          2   2023      61428.388020    27267.402891            8562.036239
5          1   2023      57357.397600    25458.179364            7724.222120
6          4   2022      61209.427902    27067.925048            9013.477503
7          3   2022      57093.487328    25391.849113            7334.888361
8          2   2022      57310.599224    25271.381289            7652.482268
9          1   2022      51195.451134    22602.156377            6843.593762
10         4   2021      53272.691552    23984.526559            7777.931586
11         3   2021      48315.596639    21816.667297            6476.075171
12         2   2021      47786.358994    22559.993448            7248.080240
13         1   2021      44690.406937    19921.990934            5899.104493
14         4   2020      49115.552469    21938.932476            7228.866063
15         3   2020      46734.010846    21367.214762            7119.135833
16         2   2020      43074.655002    19075.033670            5130.032412
17         1   2020      45348.189320    20713.713028            5728.788605
18         4   2019      51735.124745    22928.402601            6372.668451
19         3   2019      48698.552143    21666.794564            7012.677087
20         2   2019      47978.325808    22102.403535            6337.804932
21         1   2019      46247.735621    20892.290059            5714.352697
22         4   2018      50165.632932    23016.556135            7342.001549
23         3   2018      44148.103167    20236.720810            5777.478320
24         2   2018      52085.985437    22950.914246            6276.008952
25         1   2018      49712.868940    21916.687342            5882.556901
26         4   2017      55275.000000    25063.000000            7548.000000

          EBITDA
0   13922.096083
1   11943.572813
2        13149.0
3   11829.809902
4   11438.524637
5   10521.718006
6   11954.455245
7   10626.362279
8   10607.108274
9    9827.392636
10  10648.200344
11   9319.521631
12  10006.982159
13   8807.441707
14   9997.834165
15  10074.686013
16   8221.220565
17   9086.427469
18   9391.054195
19   10069.21785
20   9180.013944
21   8540.581059
22  10215.015326
23   8491.611646
24   9511.216814
25   8705.554457
26           N/A
INSERT INTO RESULTADOS VALUES(2024,2,69455.80312857535,31961.302174470737,9745.98176555364,13922.096083028468,'Global'),
(2024,1,63802.60612148751,28428.378308814594,8616.61440934002,11943.5728128699,'Global'),
(2023,4,66078.0,30475.0,9674.0,13149.0,'Global'),
(2023,3,62853.01085143204,28847.885531935073,8459.56900132275,11829.809901518796,'Global'),
(2023,2,61428.38802000759,27267.402891312213,8562.03623876235,11438.524637146691,'Global'),
(2023,1,57357.397599880795,25458.17936430975,7724.2221202024,10521.718005967907,'Global'),
(2022,4,61209.42790171153,27067.925048019468,9013.47750326499,11954.455245146693,'Global'),
(2022,3,57093.48732772651,25391.849113290347,7334.888360575071,10626.362279236262,'Global'),
(2022,2,57310.59922378635,25271.381289243713,7652.482268096298,10607.108274113332,'Global'),
(2022,1,51195.45113361231,22602.156377482057,6843.593761695654,9827.392636325114,'Global'),
(2021,4,53272.69155211626,23984.526558529866,7777.931586194914,10648.200343573077,'Global'),
(2021,3,48315.596638839466,21816.667296689317,6476.07517063645,9319.521630928804,'Global'),
(2021,2,47786.358993595255,22559.993447875506,7248.0802404757915,10006.982159271894,'Global'),
(2021,1,44690.40693672021,19921.9909338332,5899.104492809429,8807.441706916166,'Global'),
(2020,4,49115.552468539085,21938.932476289367,7228.86606319706,9997.834164877875,'Global'),
(2020,3,46734.010845961835,21367.214761846248,7119.135832770328,10074.686012719721,'Global'),
(2020,2,43074.655001929,19075.033669912315,5130.032411952074,8221.220564662008,'Global'),
(2020,1,45348.18932037066,20713.713027511836,5728.788605381143,9086.42746854843,'Global'),
(2019,4,51735.1247449662,22928.402601123445,6372.668451114874,9391.05419548701,'Global'),
(2019,3,48698.552143166955,21666.794564466232,7012.677086686622,10069.217849966226,'Global'),
(2019,2,47978.325808098336,22102.403535336995,6337.804932222957,9180.013943656655,'Global'),
(2019,1,46247.73562053852,20892.29005949488,5714.352697168594,8540.581058540392,'Global'),
(2018,4,50165.632931969056,23016.55613541045,7342.001548950003,10215.015326160235,'Global'),
(2018,3,44148.103167386806,20236.72080955599,5777.478320144682,8491.611646311303,'Global'),
(2018,2,52085.98543706606,22950.914246265816,6276.00895208458,9511.21681359364,'Global'),
(2018,1,49712.86893964255,21916.68734193612,5882.556900653713,8705.55445693481,'Global'),
(2017,4,55275.0,25063.0,7548.0,N/A,'Global'),

In [3]:
dfResultsMx=pd.read_excel(filename,2)

dfResultsMx['Trimestre']=dfResultsMx['Tiempo'].str[:1]
dfResultsMx['Tiempo']=dfResultsMx['Tiempo'].str[3:]
print(dfResultsMx.columns)

queryResultadosMx="INSERT INTO resultados VALUES"

for idx in dfResultsMx.index:
    tiempo=dfResultsMx['Tiempo'].loc[idx]
    queryResultadosMx+="({anio},{cuarto},{ingresos},{UBruta},{UOperacion},{EBI},'Mexico'),\n".format(anio=dfResultsMx['Tiempo'].loc[idx],cuarto=dfResultsMx['Trimestre'].loc[idx],ingresos=dfResultsMx['Ingresos totales'].loc[idx],UBruta=dfResultsMx['Utilidad bruta'].loc[idx],UOperacion=dfResultsMx['Utilidad de operación '].loc[idx],EBI=dfResultsMx['EBITDA Ajustado'].loc[idx])

print(queryResultadosMx)

#print(dfResultsMx)

Index(['Tiempo', 'Ingresos totales', 'Utilidad bruta',
       'Utilidad de operación ', 'EBITDA Ajustado', 'Trimestre'],
      dtype='object')
INSERT INTO resultados VALUES(2024,2,45066.53114235432,21947.50721825104,7290.669497499773,9882.158015890753,'Mexico'),
(2024,1,37844.23171576212,17888.07419070231,5681.381972133314,7743.665885295243,'Mexico'),
(2023,4,37622.0,18422.0,5618.0,7704.0,'Mexico'),
(2023,3,39035.23952123994,18688.799341222897,6031.898859612582,8182.473809876002,'Mexico'),
(2023,2,39087.65462351632,18635.445316462967,6508.8282026863935,8229.058548564464,'Mexico'),
(2023,1,33617.46280604312,15918.71768827111,5011.05954708278,6706.067336507261,'Mexico'),
(2022,4,33792.47548530963,15678.046618058166,5212.432387525795,6902.489385083605,'Mexico'),
(2022,3,33799.34620532513,15854.665684198175,5059.4911221730645,7170.912659333747,'Mexico'),
(2022,2,34475.15242874845,16494.98172440966,5726.748249617064,7533.119937699374,'Mexico'),
(2022,1,28934.917286451073,14006.818721884822,4949.790421781691,6722.426287739892,'Mexico'),
(2021,4,30791.72519381558,14918.371249672244,5082.817197610317,6835.3949481293985,'Mexico'),
(2021,3,28760.019102274735,14200.500700949957,4264.702739915021,6061.969655397579,'Mexico'),
(2021,2,30262.255526788973,15175.048615318217,5132.179968356454,6821.101330625191,'Mexico'),
(2021,1,25980.107301336437,13072.354653415612,4361.757600089908,6162.756981398439,'Mexico'),
(2020,4,27072.565038462657,13669.501429387477,4956.081815993917,6612.464861135244,'Mexico'),
(2020,3,26806.885525685047,13302.846564147489,4335.7639382954185,6175.4766800391235,'Mexico'),
(2020,2,27379.69565770218,13480.407333806475,4696.081123022391,6481.799838760074,'Mexico'),
(2020,1,25523.975031399306,12452.955307487506,3434.788591427987,5603.622026332354,'Mexico'),
(2019,4,27253.15365329295,13050.299992054011,3524.349354249953,5501.673884838423,'Mexico'),
(2019,3,28165.535440645097,13387.935044404596,4094.921157765147,5921.995458536547,'Mexico'),
(2019,2,29007.964305584348,14165.673190938416,4526.727844216127,6284.756327152787,'Mexico'),
(2019,1,24822.719061463475,11780.795196080637,3076.342306830987,4772.236775545555,'Mexico'),
(2018,4,0.0,0.0,0.0,0.0,'Mexico'),
(2018,3,0.0,0.0,0.0,0.0,'Mexico'),
(2018,2,0.0,0.0,0.0,0.0,'Mexico'),
(2018,1,0.0,0.0,0.0,0.0,'Mexico'),
(2017,4,23384.0,11203.0,3182.0,4877.0,'Mexico'),
(2019,2,29007.964305584348,14165.673190938416,4526.727844216127,6284.756327152787,'Mexico'),
(2019,1,24822.719061463475,11780.795196080637,3076.342306830987,4772.236775545555,'Mexico'),
(2018,4,0.0,0.0,0.0,0.0,'Mexico'),
(2018,3,0.0,0.0,0.0,0.0,'Mexico'),
(2018,2,0.0,0.0,0.0,0.0,'Mexico'),
(2018,1,0.0,0.0,0.0,0.0,'Mexico'),
(2017,4,23384.0,11203.0,3182.0,4877.0,'Mexico'),

In [5]:
dfResultsSa=pd.read_excel(filename,3)
dfResultsSa=dfResultsSa.transpose()
dfResultsSa.columns=dfResultsSa.iloc[0,:]
dfResultsSa=dfResultsSa.iloc[2:,:]
dfResultsSa.reset_index(names="index",inplace=True)
dfResultsSa=dfResultsSa.rename_axis(None,axis="columns")
dfResultsSa.rename(columns={"index":"Tiempo","EBITDA Ajustado (2)":"EBITDA"},inplace=True)

dfResultsSa['Trimestre']=dfResultsSa['Tiempo'].str[:1]
dfResultsSa['Tiempo']=dfResultsSa['Tiempo'].str[3:]
dfResultsSa.fillna('0',inplace=True)

print(dfResultsSa)

queryResultadosSa="INSERT INTO resultados VALUES"

for idx in dfResultsSa.index:
    row=dfResultsSa.loc[idx]
    queryResultadosSa+="({anio},{cuarto},{ingresos},{UBruta},{UOperacion},{EBI},'Sudamerica'),\n".format(anio=row['Tiempo'],cuarto=row['Trimestre'],ingresos=row['Ingresos totales'],UBruta=row['Utilidad bruta'],UOperacion=row['Utilidad de operación '],EBI=row['EBITDA'])


print(queryResultadosSa)

   Tiempo Ingresos totales Utilidad bruta Utilidad de operación        EBITDA  \
0    2024     24389.271986   10013.794956            2455.312268  4039.938067
1    2024     25958.374406   10540.304118            2935.232437  4199.906928
2    2023            28456          12054                   4056         5444
3    2023      23817.77133   10159.086191            2427.670142  3647.336092
4    2023     22340.733396    8631.957575            2053.208036  3209.466089
5    2023     23739.934794    9539.461676            2713.162573  3815.650669
6    2022     27416.952416    11389.87843            3801.045116   5051.96586
7    2022     23294.141122    9537.183429            2275.397238   3455.44962
8    2022     22835.446795    8776.399565            1925.734018  3073.988336
9    2022     22260.533847    8595.337656             1893.80334  3104.966349
10   2021     22480.966358    9066.155309            2695.114389  3812.805395
11   2021     19555.577537    7616.166596            2211.372431  3257.551976
12   2021     17524.103467    7384.944833            2115.900272  3185.880829
13   2021     18710.299635     6849.63628            1537.346893  2644.684726
14   2020      22042.98743    8269.431047            2272.784247  3385.369304
15   2020      19927.12532    8064.368198            2783.371894  3899.209333
16   2020     15694.959344    5594.626336             433.951289  1739.420726
17   2020     19824.214289     8260.75772            2294.000014  3482.805442
18   2019     24481.971092    9878.102609            2848.319097  3889.380311
19   2019     20533.016703     8278.85952            2917.755929  4147.222391
20   2019     18970.361503    7936.730344            1811.077088  2895.257617
21   2019     21425.016559    9111.494863             2638.01039  3768.344283
22   2018                0              0                      0            0
23   2018                0              0                      0            0
24   2018                0              0                      0            0
25   2018                0              0                      0            0
26   2017            25784          11425                   4137         5543

   Trimestre
0          2
1          1
2          4
3          3
4          2
5          1
6          4
7          3
8          2
9          1
10         4
11         3
12         2
13         1
14         4
15         3
16         2
17         1
18         4
19         3
20         2
21         1
22         4
23         3
24         2
25         1
26         1
INSERT INTO resultados VALUES(2024,2,24389.271986221036,10013.794956219697,2455.312268053869,4039.938067137713,'Sudamerica'),
(2024,1,25958.3744057254,10540.304118112279,2935.2324372067046,4199.906927574656,'Sudamerica'),
(2023,4,28456,12054,4056,5444,'Sudamerica'),
(2023,3,23817.771330192103,10159.086190712178,2427.6701417101676,3647.3360916427955,'Sudamerica'),
(2023,2,22340.733396491265,8631.957574849239,2053.208036075955,3209.4660885822263,'Sudamerica'),
(2023,1,23739.93479383767,9539.46167603864,2713.1625731196186,3815.6506694606464,'Sudamerica'),
(2022,4,27416.95241640189,11389.8784299613,3801.045115739195,5051.965860063089,'Sudamerica'),
(2022,3,23294.141122401383,9537.183429092165,2275.397238402006,3455.4496199025157,'Sudamerica'),
(2022,2,22835.446795037904,8776.399564834051,1925.7340184792324,3073.9883364139573,'Sudamerica'),
(2022,1,22260.533847161252,8595.337655597234,1893.8033399139629,3104.96634858522,'Sudamerica'),
(2021,4,22480.966358300673,9066.15530885762,2695.1143885845972,3812.8053954436773,'Sudamerica'),
(2021,3,19555.577536564728,7616.16659573936,2211.372430721428,3257.5519755312253,'Sudamerica'),
(2021,2,17524.103466806286,7384.944832557295,2115.900272119337,3185.880828646705,'Sudamerica'),
(2021,1,18710.29963538377,6849.636280417588,1537.3468927195217,2644.684725517728,'Sudamerica'),
(2020,4,22042.987430076424,8269.431046901882,2272.784247203143,3385.3693037426306,'Sudamerica'),
(2020,3,19927.125320276777,8064.36819769876,2783.3718944749103,3899.2093326805953,'Sudamerica'),
(2020,2,15694.959344226825,5594.626336105838,433.95128892968387,1739.4207259019347,'Sudamerica'),
(2020,1,19824.214288971358,8260.757720024332,2294.0000139531544,3482.805442216073,'Sudamerica'),
(2019,4,24481.97109167325,9878.10260906943,2848.3190968649205,3889.3803106485875,'Sudamerica'),
(2019,3,20533.01670252185,8278.859520061635,2917.7559289214746,4147.222391429679,'Sudamerica'),
(2019,2,18970.361502513984,7936.730344398575,1811.0770880068308,2895.257616503869,'Sudamerica'),
(2019,1,21425.016559075048,9111.494863414238,2638.010390337607,3768.344282994839,'Sudamerica'),
(2018,4,0,0,0,0,'Sudamerica'),
(2018,3,0,0,0,0,'Sudamerica'),
(2018,2,0,0,0,0,'Sudamerica'),
(2018,1,0,0,0,0,'Sudamerica'),
(2017,1,25784,11425,4137,5543,'Sudamerica'),

In [21]:
dfkof=pd.read_excel(filename,4)

dfkof=dfkof.transpose()
dfkof.columns=dfkof.iloc[0,:]
dfkof.reset_index(inplace=True)
#print(dfkof.columns)
print(dfkof)

Unnamed: 0       index  Transacciones (millones de transacciones)   \
0           Unnamed: 0  Transacciones (millones de transacciones)
1           Unnamed: 1                                         NaN
2              2T 2024                                 6372.795488
3              1T 2024                                 5958.003244
4              4T 2023                                      6194.6
5              3T 2023                                 6048.581099
6              2T 2023                                 5933.022568
7              1T 2023                                 5567.286363
8              4T 2022                                  5987.70124
9              3T 2022                                 5507.295969
10             2T 2022                                      5636.1
11             1T 2022                                 5205.255575
12             4T 2021                                 5564.271514
13             3T 2021                                 4891.594668
14             2T 2021                                 4659.978368
15             1T 2021                                 4375.044175
16             4T 2020                                 4924.541944
17             3T 2020                                 4185.223174
18             2T 2020                                 3636.909617
19             1T 2020                                 4652.438774
20             4T 2019                                 5333.245369
21             3T 2019                                 5037.755529
22             2T 2019                                 5012.472874
23             1T 2019                                 4837.776355
24             4T 2018                                 5186.706461
25             3T 2018                                 4973.103219
26             2T 2018                                 6699.146469
27             1T 2018                                 6137.567497
28             4T 2017                                     25875.3

Unnamed: 0  Volumen (milliones de cajas unidad)   \
0           Volumen (milliones de cajas unidad)
1                                            NaN
2                                    1095.809914
3                                    1008.632687
4                                         1056.2
5                                    1033.073778
6                                    1018.935511
7                                        939.601
8                                     995.308578
9                                     925.827227
10                                         952.4
11                                    881.625334
12                                    951.338399
13                                    854.469064
14                                    851.415553
15                                    800.655275
16                                    902.179622
17                                     807.92233
18                                    780.749527
19                                    793.545491
20                                    889.628868
21                                    842.132345
22                                    840.884159
23                                         796.1
24                                    871.726178
25                                    839.221098
26                                         977.1
27                                    907.750808
28                                        3870.6

Unnamed: 0  Precio promedio por caja unidad  Ventas netas  \
0           Precio promedio por caja unidad  Ventas netas
1                                       NaN           NaN
2                                 61.892618  69296.507901
3                                  61.21283  63637.930214
4                                     60.24         65830
5                                  58.86734   62611.95539
6                                 58.311031   61283.06363
7                                 59.275595  57145.071106
8                                 59.542344  61005.382101
9                                 60.153154  57016.624308
10                                60.046315  57190.036475
11                                 56.51779  51077.676924
12                                54.305177  53091.978985
13                                52.937723  47916.290089
14                                51.784771  47639.405601
15                                50.838001  44517.835551
16                                49.831391  49022.065501
17                                51.166682  45247.542407
18                                50.558304  42943.809047
19                                51.883517  44958.051556
20                                 52.57234  51541.125974
21                                52.089314  47294.373218
22                                52.823652  47671.844171
23                                52.574423  46021.105619
24                                52.185667  49982.250885
25                                48.953614  44011.718635
26                                50.293688  51984.528153
27                                50.685122   49595.94948
28                                    49.29      203374.0

Unnamed: 0  Otros ingresos de operación   Ingresos totales (2)  \
0           Otros ingresos de operación   Ingresos totales (2)
1                                    NaN                   NaN
2                             159.295228          69455.803129
3                             164.675908          63802.606121
4                                    248                 66078
5                             241.055461          62853.010851
6                              145.32439           61428.38802
7                             212.326493            57357.3976
8                             204.045801          61209.427902
9                               76.86302          57093.487328
10                            120.562749          57310.599224
11                             117.77421          51195.451134
12                            180.712568          53272.691552
13                             399.30655          48315.596639
14                            146.953392          47786.358994
15                            172.571386          44690.406937
16                             93.486967          49115.552469
17                           1486.468439          46734.010846
18                            130.845955          43074.655002
19                            390.137764           45348.18932
20                            193.998771          51735.124745
21                           1404.178925          48698.552143
22                            306.481637          47978.325808
23                            226.630002          46247.735621
24                            183.382046          50165.632932
25                            136.384533          44148.103167
26                            101.457284          52085.985437
27                             116.91946           49712.86894
28                                 406.0              203780.0

Unnamed: 0  Costo de ventas  Utilidad bruta  Gastos de operación   ...  \
0           Costo de ventas  Utilidad bruta  Gastos de operación   ...
1                       NaN             NaN                   NaN  ...
2              37494.500954    31961.302174          21620.579089  ...
3              35374.227813    28428.378309          19668.011631  ...
4                     35603           30475                 20413  ...
5              34005.125319    28847.885532          19969.992286  ...
6              34160.985129    27267.402891           18795.61514  ...
7              31899.218236    25458.179364          17824.884759  ...
8              34141.502854    27067.925048          17867.943902  ...
9              31701.638214    25391.849113             17933.007  ...
10             32039.217935    25271.381289          17448.256011  ...
11             28593.294756    22602.156377           15757.34874  ...
12             29288.164994    23984.526559          15904.540494  ...
13             26498.929342    21816.667297          15530.313303  ...
14             25226.365546    22559.993448           15188.94667  ...
15             24768.416003    19921.990934           13793.04151  ...
16             27176.619992    21938.932476          14374.953245  ...
17             25366.796084    21367.214762          14216.264717  ...
18             23999.621332     19075.03367          13630.475071  ...
19             24634.476293    20713.713028          14535.592758  ...
20             28806.722144    22928.402601          16018.468577  ...
21             27031.757579    21666.794564          14702.509827  ...
22             25875.922273    22102.403535          15036.421341  ...
23             25355.445561    20892.290059          14846.547753  ...
24             27149.076797    23016.556135          15164.876167  ...
25             23911.382358     20236.72081          14255.640561  ...
26             29135.071191    22950.914246          16126.412885  ...
27             27796.181598    21916.687342          15934.240828  ...
28                 112094.0         91686.0               64910.0  ...

Unnamed: 0  Resultado integral de financiamiento  Utilidad antes de impuestos  \
0           Resultado integral de financiamiento  Utilidad antes de impuestos
1                                            NaN                          NaN
2                                     885.079325                   8752.48347
3                                    1188.103968                  7505.671277
4                                           1285                         8470
5                                     552.457197                  7785.702996
6                                    1376.569277                  6926.043055
7                                    1398.867819                  6067.418527
8                                     1091.57898                  8007.845413
9                                     682.226864                  6671.408913
10                                    573.801845                  7034.096083
11                                   2193.931992                   4473.58135
12                                    748.343981                  7053.237557
13                                   1029.693971                   5169.96276
14                                   1323.241457                  5935.784512
15                                   1131.364516                  4765.899303
16                                   1777.072381                  5375.071781
17                                   1421.285139                  3898.918626
18                                    1267.97286                  2889.349433
19                                    2196.04732                   3612.77833
20                                   1506.832994                    3851.4571
21                                   1429.910166                  5564.128923
22                                   1558.736481                  4778.913073
23                                   1593.415492                  4079.425544
24                                   2149.017219                  4603.318128
25                                   1322.217212                   4393.86605
26                                   1380.665798                  4854.463784
27                                    2071.86932                  3737.204879
28                                        5276.0                      -7101.0

Unnamed: 0    Impuestos  Resultado de operaciones discontinuas  \
0             Impuestos  Resultado de operaciones discontinuas
1                   NaN                                    NaN
2           3043.634785                                    0.0
3           2258.208578                                    0.0
4                  2802                                    -
5           2272.834351                                    0.0
6           1881.148535                                    0.0
7           1989.246378                                    0.0
8            611.359432                                    0.0
9           2166.342391                                    0.0
10          2458.344444                                    0.0
11          1320.943616                                    0.0
12            977.65398                                    0.0
13          1696.912499                                    0.0
14          2267.507808                                    0.0
15          1659.594101                                    0.0
16          1997.240319                                    0.0
17          1320.094836                                    0.0
18           969.488361                                    0.0
19          1122.016737                                    0.0
20          1694.092112                                    0.0
21          1439.178637                                    0.0
22          1181.196245                                    0.0
23          1330.913107                                    0.0
24          1385.892952                            2790.316187
25          1381.737452                             409.699735
26          1663.570577                                    NaN
27           1196.26376                                    NaN
28               4554.0                                    NaN

Unnamed: 0  Utilidad neta consolidada  \
0           Utilidad neta consolidada
1                                 NaN
2                         5708.848686
3                         5247.462698
4                                5669
5                         5512.868645
6                          5044.89452
7                         4078.172149
8                         7396.485982
9                         4505.066522
10                        4575.751639
11                        3152.637733
12                        6075.583577
13                        3473.050261
14                        3668.276704
15                        3106.305201
16                        3377.831462
17                        2578.823791
18                        1919.861072
19                        2490.761594
20                        2157.364988
21                        4124.950287
22                        3597.716828
23                        2748.512437
24                        6007.741363
25                        3421.828333
26                        3190.893207
27                        2540.941118
28                           -11654.0

Unnamed: 0 Utilidad neta atribuible a la participación controladora  \
0           Utilidad neta atribuible a la participación co...
1                                                         NaN
2                                                  5607.99565
3                                                 5006.107188
4                                                        5392
5                                                 5380.071213
6                                                  4926.16062
7                                                 3916.014293
8                                                 7143.747122
9                                                 4374.111649
10                                                4626.687246
11                                                  2893.8239
12                                                5808.642803
13                                                 3419.24101
14                                                3316.344772
15                                                3155.595621
16                                                3177.062072
17                                                2462.812918
18                                                2114.689793
19                                                 2551.74939
20                                                1995.459539
21                                                4026.871158
22                                                3486.946391
23                                                2590.465135
24                                                5541.093824
25                                                 3266.06602
26                                                2780.665922
27                                                2413.795189
28                                                   -12802.0

Unnamed: 0  Participación no controladora  NaN  NaN        En hoja:
0           Participación no controladora  NaN  NaN        En hoja:
1                                     NaN  NaN  NaN  KOF consolidado
2                              100.853036  NaN  NaN              NaN
3                              241.355511  NaN  NaN              NaN
4                                     277  NaN  NaN              NaN
5                              132.797432  NaN  NaN              NaN
6                                118.7339  NaN  NaN              NaN
7                              162.157856  NaN  NaN              NaN
8                               252.73886  NaN  NaN              NaN
9                              130.954874  NaN  NaN              NaN
10                             -50.935607  NaN  NaN              NaN
11                             258.813833  NaN  NaN              NaN
12                             266.940774  NaN  NaN              NaN
13                              53.809251  NaN  NaN              NaN
14                             351.931932  NaN  NaN              NaN
15                              -49.29042  NaN  NaN              NaN
16                              200.76939  NaN  NaN              NaN
17                             116.010873  NaN  NaN              NaN
18                            -194.828721  NaN  NaN              NaN
19                             -60.987796  NaN  NaN              NaN
20                             161.905449  NaN  NaN              NaN
21                              98.079129  NaN  NaN              NaN
22                             110.770437  NaN  NaN              NaN
23                             158.047302  NaN  NaN              NaN
24                             466.647539  NaN  NaN              NaN
25                             155.762313  NaN  NaN              NaN
26                             410.227285  NaN  NaN              NaN
27                              127.14593  NaN  NaN              NaN
28                                 1148.0  NaN  NaN              NaN

[29 rows x 31 columns]